# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeepLinkFromPushNotification' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DeepLinkFromPushNotification
  pod 'FirebaseMessaging'
  pod 'Firebase/Core'

  target 'DeepLinkFromPushNotification-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DeepLinkFromPushNotificationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
